import { prisma } from "@/app/lib/prisma";

async function main() {
  const cars = [
    {
      title: "Sedán Económico",
      image: "/images/sedan-economico.png",
      description: "Ideal para ciudad.",
      tag: "Usado",
      price: 15000,
      category: "Sedán",
      model: "Toyota Corolla",
      year: 2020,
      km: 11000,
      features: ["Motor 1.6L", "Aire acondicionado", "Frenos ABS"],
      specifications: { Potencia: "120 HP", Transmisión: "Manual", Combustible: "Gasolina" },
      gallery: ["/images/sedan1.png", "/images/sedan2.png"],
      financingOptions: [{ plan: "Básico", details: "30% inicial, 24 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "SUV Familiar",
      image: "/images/suv-familiar.png",
      description: "Espacio y comodidad.",
      tag: "Nuevo",
      price: 25000,
      category: "SUV",
      model: "Toyota RAV4",
      year: 2021,
      km: 28000,
      features: ["Motor 2.0L", "Tracción integral", "Espacio para 7 pasajeros"],
      specifications: { Potencia: "180 HP", Transmisión: "Automática", Combustible: "Diesel" },
      gallery: ["/images/suv1.png", "/images/suv2.png"],
      financingOptions: [{ plan: "Premium", details: "15% inicial, 60 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Deportivo Elegante",
      image: "/images/deportivo-elegante.png",
      description: "Velocidad y estilo.",
      tag: "Oferta",
      price: 35000,
      category: "Deportivo",
      model: "Toyota Supra",
      year: 2022,
      km: 55000,
      features: ["Motor V6", "Turbo", "Suspensión deportiva"],
      specifications: { Potencia: "350 HP", Transmisión: "Automática", Combustible: "Gasolina" },
      gallery: ["/images/deportivo1.png", "/images/deportivo2.png"],
      financingOptions: [{ plan: "Elite", details: "20% inicial, 48 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Camioneta 4x4",
      image: "/images/camioneta.png",
      description: "Potencia para cualquier terreno.",
      tag: "Destacado",
      price: 45000,
      category: "Camioneta",
      model: "Toyota Hilux",
      year: 2023,
      km: 70000,
      features: ["Tracción 4x4", "Alta capacidad de carga", "Sistema de navegación"],
      specifications: { Potencia: "250 HP", Transmisión: "Automática", Combustible: "Diesel" },
      gallery: ["/images/camioneta1.png", "/images/camioneta2.png"],
      financingOptions: [{ plan: "Full", details: "20% inicial, 60 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Coupé Premium",
      image: "/images/coupe-premium.png",
      description: "Diseño sofisticado.",
      tag: "Nuevo",
      price: 55000,
      category: "Coupé",
      model: "Toyota GT86",
      year: 2024,
      km: 95000,
      features: ["Diseño aerodinámico", "Tecnología avanzada", "Luces LED"],
      specifications: { Potencia: "300 HP", Transmisión: "Automática", Combustible: "Gasolina" },
      gallery: ["/images/coupe1.png", "/images/coupe2.png"],
      financingOptions: [{ plan: "Premium Coupé", details: "20% inicial, 60 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Furgón Comercial",
      image: "/images/furgon.png",
      description: "Carga y equipamiento.",
      tag: "Usado",
      price: 65000,
      category: "Furgón",
      model: "Toyota Hiace",
      year: 2025,
      km: 100000,
      features: ["Amplio maletero", "Eficiencia en consumo", "Durabilidad"],
      specifications: { Potencia: "150 HP", Transmisión: "Manual", Combustible: "Diesel" },
      gallery: ["/images/furgon1.png", "/images/furgon2.png"],
      financingOptions: [{ plan: "Económico", details: "20% inicial, 48 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Hatchback Urbano",
      image: "/images/hatchback.png",
      description: "Compacto y eficiente.",
      tag: "Oferta",
      price: 75000,
      category: "Hatchback",
      model: "Toyota Yaris",
      year: 2026,
      km: 190000,
      features: ["Motor eficiente", "Maniobrabilidad", "Bajo consumo"],
      specifications: { Potencia: "100 HP", Transmisión: "Manual", Combustible: "Gasolina" },
      gallery: ["/images/hatchback1.png", "/images/hatchback2.png"],
      financingOptions: [{ plan: "Oferta", details: "10% inicial, 24 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Pick-up Dual",
      image: "/images/pickup.png",
      description: "Trabajo y familia.",
      tag: "Destacado",
      price: 85000,
      category: "Pick-up",
      model: "Toyota Tacoma",
      year: 2027,
      km: 110000,
      features: ["Altura libre", "Capacidad todoterreno", "Espacio interior"],
      specifications: { Potencia: "220 HP", Transmisión: "Automática", Combustible: "Gasolina" },
      gallery: ["/images/pickup1.png", "/images/pickup2.png"],
      financingOptions: [{ plan: "Avanzado", details: "20% inicial, 72 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
    {
      title: "Coupe Deportivo",
      image: "/images/coupe-deportivo.png",
      description: "Rápido en pista.",
      tag: "Nuevo",
      price: 95000,
      category: "Coupé",
      model: "Toyota GR86",
      year: 2028,
      km: 200000,
      features: ["Motor turbo", "Asientos deportivos", "Tecnología avanzada"],
      specifications: { Potencia: "400 HP", Transmisión: "Automática", Combustible: "Gasolina" },
      gallery: ["/images/coupe-deportivo1.png", "/images/coupe-deportivo2.png"],
      financingOptions: [{ plan: "Elite Deportivo", details: "30% inicial, 48 meses" }],
      youtubeUrl: ["https://youtube.com/watch?v=0IrFAFPNoc0"],
    },
  ];

  for (const car of cars) {
    await prisma.car.create({ data: car });
  }

  console.log("Datos de vehículos cargados correctamente.");
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });